plugin:
    name: 'hon.honcuratorreview::lang.plugin.name'
    description: 'hon.honcuratorreview::lang.plugin.description'
    author: HON
    icon: oc-icon-comments-o
    homepage: ''
navigation:
    main-Review-item:
        label: 'hon.honcuratorreview::lang.plugin.name'
        url: hon/honcuratorreview/reviews
        icon: icon-star-half-full
        sideMenu:
            reviews-menu-item:
                label: Reviews
                url: hon/honcuratorreview/reviews
                icon: icon-star
            question-menu-item:
                label: Questions
                url: /hon/honcuratorreview/questions
                icon: icon-question-circle
            tags-menu-item:
                label: Tags
                url: hon/honcuratorreview/tags
                icon: icon-tags
            services-menu-item:
                label: Services
                url: hon/honcuratorreview/services
                icon: icon-globe
            platforms-menu-item:
                label: Platforms
                url: hon/honcuratorreview/platforms
                icon: icon-sitemap
