# ===================================
#  Relation Behavior Config
# ===================================

reviews:
    label: Reviews
    view:
        list: $/hon/honcuratorreview/models/review/columns.yaml