title: Questions
modelClass: HON\HonCuratorReview\Models\Question
list: $/hon/honcuratorreview/models/question/columns.yaml
recordUrl: 'hon/honcuratorreview/questions/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
