list: $/hon/honcuratorreview/models/platform/columns.yaml
modelClass: HON\HonCuratorReview\Models\Platform
title: Platforms
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'hon/honcuratorreview/platforms/update/:id'
