# ===================================
#  Relation Behavior Config
# ===================================

platforms:
    label: Platforms
    view:
        list: $/hon/honcuratorreview/models/platformservicepivot/columns.yaml
        toolbarButtons: add|remove
    manage:
        list: $/hon/honcuratorreview/models/platform/columns.yaml
        toolbarButtons: add|remove
    pivot:
        form: $/hon/honcuratorreview/models/platformservicepivot/fields.yaml