list: $/hon/honcuratorreview/models/review/columns.yaml
modelClass: HON\HonCuratorReview\Models\Review
title: Reviews
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'hon/honcuratorreview/reviews/update/:id'
recordsPerPage: 20